import { DB } from '../core/db.js';
import { session } from '../core/state.js';

// ⚡ Diambil dari Word: MONITORING & LOG
export function renderMonitoring() {
    const isGuru = session.role === 'guru';
    const ujianAktif = DB.ujian.filter(u => u.status === 'aktif' && (!isGuru || u.guruId === session.user));
    const pesertaAktif = isGuru ? DB.aktifLog.filter(a => ujianAktif.some(u => u.nama.includes(a.ujian) || a.ujian.includes(u.mapel))) : DB.aktifLog;
    const pesertaSelesai = DB.hasil.filter(h => isGuru ? DB.ujian.find(u => u.id === h.ujianId && u.guruId === session.user) : true).slice(0, 5).map(h => { const uj = DB.ujian.find(u => u.id === h.ujianId); return { siswa: h.nama, kelas: DB.users[h.siswaId]?.kelas||'—', ujian: uj?.nama||h.ujianId, progress: (h.benar+h.salah), total: (h.benar+h.salah+h.kosong)||10, status: 'selesai', waktuMulai: h.waktu?.split(' ')[1]?.slice(0,5)||'—', nilai: h.nilai, pelanggaran: h.pelanggaran }; });
    const semuaPeserta = [...pesertaAktif, ...pesertaSelesai];
    const totalAktif = pesertaAktif.filter(p => p.status !== 'selesai').length;
    document.getElementById('main-content').innerHTML = `
    <div class="page-header flex justify-between items-center"><div><div class="page-title">👁️ Monitoring Live</div><div class="page-subtitle">Pantau peserta ujian${isGuru?' ujian saya':''} secara real-time</div></div><button class="btn btn-ghost btn-sm" onclick="window.renderMonitoring()" title="Refresh">🔄 Refresh</button></div>
    <div class="grid-4 mb-4"><div class="stat-card blue"><div class="stat-icon">📋</div><div class="stat-value">${ujianAktif.length}</div><div class="stat-label">Ujian Aktif</div></div><div class="stat-card green"><div class="stat-icon">👤</div><div class="stat-value">${totalAktif}</div><div class="stat-label">Sedang Mengerjakan</div></div><div class="stat-card yellow"><div class="stat-icon">⚠️</div><div class="stat-value">${pesertaAktif.filter(p=>p.status==='peringatan').length}</div><div class="stat-label">Ada Peringatan</div></div><div class="stat-card red"><div class="stat-icon">✅</div><div class="stat-value">${pesertaSelesai.length}</div><div class="stat-label">Selesai Hari Ini</div></div></div>
    ${ujianAktif.length>0?`<div class="card mb-4"><div class="card-header"><div class="card-title">📋 Ujian Sedang Berlangsung</div><span class="badge badge-green animate-pulse">● LIVE</span></div><div style="display:flex;flex-direction:column;gap:8px;">${ujianAktif.map(u=>{ const guru=DB.users[u.guruId]; const peserta=DB.hasil.filter(h=>h.ujianId===u.id).length; return `<div style="display:flex;align-items:center;justify-content:space-between;padding:10px 14px;background:var(--bg2);border:1px solid rgba(110,231,183,0.25);border-radius:var(--radius-sm);"><div><div style="font-size:13px;font-weight:700;">${u.nama}</div><div style="font-size:11px;color:var(--text3);">${u.kelas} • Token: <span class="font-mono">${u.token}</span>${!isGuru&&guru?` • Guru: ${guru.nama}`:''}</div></div><div style="text-align:right;"><div style="font-size:12px;color:var(--accent2);font-weight:600;">${peserta} sudah selesai</div><div style="font-size:11px;color:var(--text3);">${u.durasi} menit</div></div></div>`; }).join('')}</div></div>`:`<div class="alert alert-info mb-4"><span>📭</span><span>Tidak ada ujian yang sedang berlangsung${isGuru?' untuk ujian Anda':''}.</span></div>`}
    <div class="card-title mb-3" style="font-size:15px;font-weight:700;">👥 Status Peserta</div>
    ${semuaPeserta.length===0?`<div class="card"><div class="empty-state" style="padding:40px;"><div class="empty-state-icon">👤</div><div class="empty-state-text">Belum ada peserta yang aktif atau selesai.</div></div></div>`:`<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px;">${semuaPeserta.map(a=>`<div class="card" style="border-color:${a.status==='peringatan'?'rgba(245,158,11,0.4)':a.status==='selesai'?'rgba(110,231,183,0.25)':'rgba(79,142,247,0.3)'};"><div class="flex justify-between items-center mb-2"><div class="flex items-center gap-2"><div class="monitor-dot ${a.status==='peringatan'?'warning':a.status==='selesai'?'offline':''}"></div><span style="font-size:13px;font-weight:700;">${a.siswa}</span></div><span class="badge ${a.status==='peringatan'?'badge-yellow':a.status==='selesai'?'badge-green':'badge-blue'}">${a.status==='peringatan'?'⚠️ Peringatan':a.status==='selesai'?`✅ Nilai: ${a.nilai??'—'}`:'● Aktif'}</span></div><div style="font-size:12px;color:var(--text3);margin-bottom:8px;">${a.kelas} • ${a.ujian}</div><div class="flex justify-between text-sm mb-1"><span class="text-muted">Progress Soal</span><span class="font-mono">${a.progress}/${a.total}</span></div><div class="progress mb-2"><div class="progress-bar ${a.status==='selesai'?'progress-bar-green':'progress-bar-blue'}" style="width:${Math.min(100,Math.round(a.progress/a.total*100))}%"></div></div><div class="flex justify-between text-xs text-muted"><span>⏰ ${a.status==='selesai'?'Selesai':'Mulai'}: ${a.waktuMulai}</span>${a.pelanggaran>0?`<span class="text-warn">⚠️ ${a.pelanggaran}x pelanggaran</span>`:a.status==='peringatan'?'<span class="text-warn">Pindah tab terdeteksi</span>':''}</div></div>`).join('')}</div>`}`;
}

export function renderLogAktivitas() {
    const logs = [
        { time: '08:42:15', type: 'warn', icon: '⚠️', msg: 'Bella Putri berpindah tab saat UTS Fisika (pelanggaran #1)' },
        { time: '08:35:00', type: 'info', icon: '▶️', msg: 'Ahmad Fauzi memulai UTS Fisika (token: FIS456)' },
        { time: '08:35:22', type: 'info', icon: '▶️', msg: 'Bella Putri memulai UTS Fisika (token: FIS456)' },
        { time: '08:36:01', type: 'info', icon: '▶️', msg: 'Candra Wijaya memulai UTS Fisika (token: FIS456)' },
        { time: '08:00:00', type: 'success', icon: '📋', msg: 'Ujian UTS Fisika diaktifkan oleh guru.fisika' },
        { time: '07:55:00', type: 'info', icon: '🔑', msg: 'Admin login ke sistem' },
    ];
    document.getElementById('main-content').innerHTML = `<div class="page-header"><div class="page-title">📜 Log Aktivitas</div><div class="page-subtitle">Rekam jejak seluruh aktivitas sistem dan ujian</div></div><div class="card">${logs.map(l => `<div class="log-item"><span class="log-time">${l.time}</span><span>${l.icon}</span><span style="font-size:13px;color:var(--text);">${l.msg}</span></div>`).join('')}</div>`;
}
